analytics: {}
color:
  brandColors:
    - '#4d585a'
    - '#ff9e19'
    - '#a0793b'
    - '#000000'
    - '#005555'
  brandStrength: 1
  lightness: 0.5
  rhythmicContrast: 0.5
  saturation: 0.5
cta: {}
layout_spectrum: 0.908783
name: Heritage Window Covering Services
opengraph: {}
purpose:
  - name: sign-ups
typography_spectrum: 0.48852
